### ISSUE TITLE
Issue while running preprocess.sh on java-small DB

### ISSUE THREAD

**Issue by sakshi15108** [tech-srl/code2vec#103]
I tried the following: 
1. downloaded java-small
2. provided the complete paths to TRAIN_DIR, VAL_DIR, TEST_DIR in preprocess.sh
3. source preprocess.sh

I am running into errors because:
preprocess.sh is calling JavaExtractor/extract.py without any --file argument. Whereas, extract.py requires --file argument.
 
Error:

> Extracting paths from validation set...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/sak/Desktop/code2vec/JavaExtractor/extract.py", line 24, in ParallelExtractDir
    ExtractFeaturesForDir(args, dir, "")
  File "/home/sak/Desktop/code2vec/JavaExtractor/extract.py", line 38, in ExtractFeaturesForDir
    sleeper = subprocess.Popen(command, stdout=outputFile, stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'
"""

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
>   File "/home/sak/Desktop/code2vec/JavaExtractor/extract.py", line 103, in <module>
>     ExtractFeaturesForDirsList(args, to_extract)
>   File "/home/sak/Desktop/code2vec/JavaExtractor/extract.py", line 69, in ExtractFeaturesForDirsList
>     p.starmap(ParallelExtractDir, zip(itertools.repeat(args), dirs))
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'
> Finished extracting paths from validation set
> Extracting paths from test set...

**Comment by urialon** [comment]
Hi @sakshi15108 ,
Thank you for your interest in code2vec!

I think that you don't have JDK installed, so the system does not recognize the command `java`.

Uri

**Comment by urialon** [comment]
Closing due to inactivity, but feel free to re-open if you have additional questions.
