### ISSUE TITLE
Preprocess.sh error (division by Zero)

### ISSUE THREAD

**Issue by ShaliniR11** [tech-srl/code2vec#158]
Hi Dr.Alon,
 I have my own Java dataset and I am trying to preprocess it with the given Script. I have changed the path directories in the script.I get the following output:
shali@DESKTOP-JNLA5ED MINGW64 ~/Documents/Git/code2vec (master)
$ sh preprocess.sh
preprocess.sh: line 21: C:/Users/shali/Documents/Git/code2vec/data/javadata/train/: Is a directory
Extracting paths from validation set...
Finished extracting paths from validation set
Extracting paths from test set...
Finished extracting paths from test set
Extracting paths from training set...
Finished extracting paths from training set
Creating histograms from the training data
File: my_dataset.test.raw.txt
Traceback (most recent call last):
  File "C:\Users\shali\Documents\Git\code2vec\preprocess.py", line 133, in <module>
    num_examples = process_file(file_path=data_file_path, data_file_role=data_role, dataset_name=args.output_name,
  File "C:\Users\shali\Documents\Git\code2vec\preprocess.py", line 69, in process_file
    print('Average total contexts: ' + str(float(sum_total) / total))
ZeroDivisionError: float division by zero.

My System Requirements:
I am using GitBash on Visual studio code to run the script. 
OS: Windows 11
Java : java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
Python: python --version
Python 3.10.4
CUDA:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
below is my preprocess.sh in txt format
[preprocess.txt](https://github.com/tech-srl/code2vec/files/9133359/preprocess.txt)

Please let me know how to proceed further.

**Comment by urialon** [comment]
Hi @ShaliniR11 ,
Sorry for the delayed response.

Did you notice that you have a "space" token in line 21, right before the path? can you delete this space and see if it helps?

Additionally, do you have subdirectories in the directory `C:/Users/shali/Documents/Git/code2vec/data/javadata/train/`? The code looks for subdirectories in the training path.

Best,
Uri

**Comment by ShaliniR11** [comment]
Hi Dr. Alon, I have tried removing the space, the error still exists.
I have a single sub directory in each of train,test and val like
![Screenshot (29)](https://user-images.githubusercontent.com/89750136/180662723-d6c24747-3c6b-4196-92a1-1d1dce99ee58.png)

and inside these subdirectories I have java files like this:
![Screenshot (30)](https://user-images.githubusercontent.com/89750136/180662770-390668d8-1ad8-46b5-9e44-b13036de1c74.png)

**Comment by urialon** [comment]
Can you try running the java process directly, e.g.,:
```
java -cp JavaExtractor/JPredict/target/JavaExtractor-0.0.1-SNAPSHOT.jar JavaExtractor.App --max_path_length 8 --max_path_width 2 --dir JavaExtractor/JPredict/src/main
```
?

**Comment by ShaliniR11** [comment]
> Can you try running the java process directly, e.g.,:
> 
> ```
> java -cp JavaExtractor/JPredict/target/JavaExtractor-0.0.1-SNAPSHOT.jar JavaExtractor.App --max_path_length 8 --max_path_width 2 --dir JavaExtractor/JPredict/src/main
> ```
> 
> ?
This is the console output:
![image](https://user-images.githubusercontent.com/89750136/180674268-0d6a1b13-cfc4-4b68-89b0-4934626ec4fa.png)

**Comment by urialon** [comment]
OK so the base java process is running fine, it looks like the problem is in some input/output redirection because of Windows.
Can you try running that on a linux machine, or BashOnWindows?

**Comment by zunairazaman2021** [comment]
Hi urialon I am facing the same issue. @ShaliniR11  could you solve it?
(env_tensor) zunaira@snps-ubo9fomrduif C2V3 % source preprocess.sh
Extracting paths from validation set...
Finished extracting paths from validation set
Extracting paths from test set...
Finished extracting paths from test set
Extracting paths from training set...
Finished extracting paths from training set
Creating histograms from the training data
File: my_dataset.test.raw.txt
Traceback (most recent call last):
  File "/Users/zunaira/Downloads/C2V3/preprocess.py", line 133, in <module>
    num_examples = process_file(file_path=data_file_path, data_file_role=data_role, dataset_name=args.output_name,
  File "/Users/zunaira/Downloads/C2V3/preprocess.py", line 69, in process_file
    print('Average total contexts: ' + str(float(sum_total) / total))
ZeroDivisionError: float division by zero

**Comment by urialon** [comment]
Hi @zunairazaman2021 ,
Thank you for your interest in our work!

Can you try running the java process directly, as instructed earlier in this thread?

**Comment by zunairazaman2021** [comment]
@urialon Yes I did 
<img width="1728" alt="Screenshot 2023-02-08 at 11 57 22" src="https://user-images.githubusercontent.com/47628487/217523459-66abf07e-1f3b-4660-bd36-3fca908fb503.png">

**Comment by zunairazaman2021** [comment]
This is the preprocess.sh file 
`#!/usr/bin/env bash
###########################################################
# Change the following values to preprocess a new dataset.
# TRAIN_DIR, VAL_DIR and TEST_DIR should be paths to      
#   directories containing sub-directories with .java files
#   each of {TRAIN_DIR, VAL_DIR and TEST_DIR} should have sub-dirs,
#   and data will be extracted from .java files found in those sub-dirs).
# DATASET_NAME is just a name for the currently extracted 
#   dataset.                                              
# MAX_CONTEXTS is the number of contexts to keep for each 
#   method (by default 200).                              
# WORD_VOCAB_SIZE, PATH_VOCAB_SIZE, TARGET_VOCAB_SIZE -   
#   - the number of words, paths and target words to keep 
#   in the vocabulary (the top occurring words and paths will be kept). 
#   The default values are reasonable for a Tesla K80 GPU 
#   and newer (12 GB of board memory).
# NUM_THREADS - the number of parallel threads to use. It is 
#   recommended to use a multi-core machine for the preprocessing 
#   step and set this value to the number of cores.
# PYTHON - python3 interpreter alias.
TRAIN_DIR=/Users/zunaira/Downloads/C2V3/tmp/train
VAL_DIR=/Users/zunaira/Downloads/C2V3/tmp/validation
TEST_DIR=/Users/zunaira/Downloads/C2V3/tmp/test
DATASET_NAME=my_dataset
MAX_CONTEXTS=200
WORD_VOCAB_SIZE=1301136
PATH_VOCAB_SIZE=911417
TARGET_VOCAB_SIZE=261245
NUM_THREADS=64
PYTHON=python3
###########################################################

TRAIN_DATA_FILE=${DATASET_NAME}.train.raw.txt
VAL_DATA_FILE=${DATASET_NAME}.val.raw.txt
TEST_DATA_FILE=${DATASET_NAME}.test.raw.txt
EXTRACTOR_JAR=JavaExtractor/JPredict/target/JavaExtractor-0.0.1-SNAPSHOT.jar
#EXTRACTOR_JAR=JavaExtractor/javaExtractor-master/target/javaExtractor-1.0.jar


mkdir -p data
mkdir -p data/${DATASET_NAME}

echo "Extracting paths from validation set..."
${PYTHON} JavaExtractor/extract.py --dir ${VAL_DIR} --max_path_length 8 --max_path_width 2 --num_threads ${NUM_THREADS} --jar ${EXTRACTOR_JAR} > ${VAL_DATA_FILE}
echo "Finished extracting paths from validation set"
echo "Extracting paths from test set..."
${PYTHON} JavaExtractor/extract.py --dir ${TEST_DIR} --max_path_length 8 --max_path_width 2 --num_threads ${NUM_THREADS} --jar ${EXTRACTOR_JAR} > ${TEST_DATA_FILE}
echo "Finished extracting paths from test set"
echo "Extracting paths from training set..."
${PYTHON} JavaExtractor/extract.py --dir ${TRAIN_DIR} --max_path_length 8 --max_path_width 2 --num_threads ${NUM_THREADS} --jar ${EXTRACTOR_JAR} | shuf > ${TRAIN_DATA_FILE}
echo "Finished extracting paths from training set"

TARGET_HISTOGRAM_FILE=data/${DATASET_NAME}/${DATASET_NAME}.histo.tgt.c2v
ORIGIN_HISTOGRAM_FILE=data/${DATASET_NAME}/${DATASET_NAME}.histo.ori.c2v
PATH_HISTOGRAM_FILE=data/${DATASET_NAME}/${DATASET_NAME}.histo.path.c2v

echo "Creating histograms from the training data"
cat ${TRAIN_DATA_FILE} | cut -d' ' -f1 | awk '{n[$0]++} END {for (i in n) print i,n[i]}' > ${TARGET_HISTOGRAM_FILE}
cat ${TRAIN_DATA_FILE} | cut -d' ' -f2- | tr ' ' '\n' | cut -d',' -f1,3 | tr ',' '\n' | awk '{n[$0]++} END {for (i in n) print i,n[i]}' > ${ORIGIN_HISTOGRAM_FILE}
cat ${TRAIN_DATA_FILE} | cut -d' ' -f2- | tr ' ' '\n' | cut -d',' -f2 | awk '{n[$0]++} END {for (i in n) print i,n[i]}' > ${PATH_HISTOGRAM_FILE}

${PYTHON} preprocess.py --train_data ${TRAIN_DATA_FILE} --test_data ${TEST_DATA_FILE} --val_data ${VAL_DATA_FILE} \
  --max_contexts ${MAX_CONTEXTS} --word_vocab_size ${WORD_VOCAB_SIZE} --path_vocab_size ${PATH_VOCAB_SIZE} \
  --target_vocab_size ${TARGET_VOCAB_SIZE} --word_histogram ${ORIGIN_HISTOGRAM_FILE} \
  --path_histogram ${PATH_HISTOGRAM_FILE} --target_histogram ${TARGET_HISTOGRAM_FILE} --output_name data/${DATASET_NAME}/${DATASET_NAME}
    
# If all went well, the raw data files can be deleted, because preprocess.py creates new files 
# with truncated and padded number of paths for each example.

#rm ${TRAIN_DATA_FILE} ${VAL_DATA_FILE} ${TEST_DATA_FILE} ${TARGET_HISTOGRAM_FILE} ${ORIGIN_HISTOGRAM_FILE} \
# ${PATH_HISTOGRAM_FILE}`

**Comment by zunairazaman2021** [comment]
Using #109  I get data stored in a tmp directory but still c2v and raw.txt files are empty. :( 
<img width="1728" alt="Screenshot 2023-02-08 at 11 57 22" src="https://user-images.githubusercontent.com/47628487/217529324-ee770583-7f9f-4c39-9d7f-791a1e3320b1.png">

**Comment by urialon** [comment]
Great to hear :-)

**Comment by Lufedi** [comment]
+1 on https://github.com/tech-srl/code2vec/pull/109 solution, I had the same issue and the PR from [gOATiful](https://github.com/gOATiful) made it work

**Comment by urialon** [comment]
Thanks @Lufedi and @zunairazaman2021 , I merged that PR.
