### ISSUE TITLE
I run this "python3 code2vec.py --load models/dataset/saved_model_iter2 --test data/dataset/dataset.test.c2v" and I got this issue! is there any help?

### ISSUE THREAD

**Issue by alsabaawi** [tech-srl/code2vec#169]
/job:localhost/replica:0/task:0/device:GPU:0 with 22297 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:21:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "code2vec.py", line 19, in <module>
    model = load_model_dynamically(config)
  File "code2vec.py", line 13, in load_model_dynamically
    return Code2VecModel(config)
  File "/home/alsabaaw/code2vec/tensorflow_model.py", line 38, in __init__
    super(Code2VecModel, self).__init__(config)
  File "/home/alsabaaw/code2vec/model_base.py", line 46, in __init__
    self.vocabs = Code2VecVocabs(config)
  File "/home/alsabaaw/code2vec/vocabularies.py", line 161, in __init__
    self._load_or_create()
  File "/home/alsabaaw/code2vec/vocabularies.py", line 170, in _load_or_create
    self._create_from_word_freq_dict()
  File "/home/alsabaaw/code2vec/vocabularies.py", line 188, in _create_from_word_freq_dict
    word_freq_dict = self._load_word_freq_dict()
  File "/home/alsabaaw/code2vec/vocabularies.py", line 221, in _load_word_freq_dict
    with open(self.config.word_freq_dict_path, 'rb') as file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by urialon** [comment]
Hi @alsabaawi ,

Which model are you trying to load?
What happens if you are loading our trained models?

Best,
Uri

**Comment by alsabaawi** [comment]
Hi Uri,

Do you mean Keras or TensorFlow models? I used the default one, I did not change anything except the paths.
But I am sorry becasue this is for "https://github.com/anki54/code2vec"

Thanks,

Aiman

**Comment by urialon** [comment]
What do you mean?
Are you trying to run the code in this repository or another repository?

**Comment by alsabaawi** [comment]
I run it on the university server (GPU)

**Comment by alsabaawi** [comment]
Was this your question?
