### ISSUE TITLE
[Bug] Undefined tensor name "shuffle_batch/random_shuffle_queue_Size:0"

### ISSUE THREAD

**Issue by iTakeshi** [tech-srl/code2vec#30]
When running current master 01d1731, the script throws an error on an undefined tensor name:

https://github.com/tech-srl/code2vec/blob/01d17316b2702893296267c400b895ee6277131e/tensorflow_model.py#L85-L86

Commenting-out these 2 lines solves the problem.

**Comment by iTakeshi** [comment]
backtrace:

```
2019-08-06 17:23:09,072 INFO     Initalized variables
2019-08-06 17:23:10,585 INFO     Started reader...
2019-08-06 17:23:11.074339: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2019-08-06 17:23:48,832 INFO     Average loss at batch 100: 0.010818, 	throughput: 1650 samples/sec
Traceback (most recent call last):
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 303, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3476, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3518, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'shuffle_batch/random_shuffle_queue_Size:0' refers to a Tensor which does not exist. The operation, 'shuffle_batch/random_shuffle_queue_Size', does not exist in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2vec.py", line 23, in <module>
    model.train()
  File "/home/itakeshi/projects/code2vec/tensorflow_model.py", line 86, in train
    "shuffle_batch/random_shuffle_queue_Size:0"))
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1158, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 274, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/itakeshi/projects/code2vec/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 313, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'shuffle_batch/random_shuffle_queue_Size:0' cannot be interpreted as a Tensor. ("The name 'shuffle_batch/random_shuffle_queue_Size:0' refers to a Tensor which does not exist. The operation, 'shuffle_batch/random_shuffle_queue_Size', does not exist in the graph.")
```

**Comment by urialon** [comment]
This is correct, thank you. 
@eladn has recently updated the reader to use the tf.data.Dataset API, which does no longer have the  "shuffle_batch/random_shuffle_queue_Size:0" op.

Thank you for letting us know, I uncommented these lines in master.
