### ISSUE TITLE
Question about Dataset

### ISSUE THREAD

**Issue by lishi0927** [tech-srl/code2vec#48]
Hello, I'm interested in this project.
But when I try to evaluate your network through your java14m dataset, there is a small error in the Dataset.map function in the self._create_dataset_pipeline. The error is "TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.".
Coud you give me some help for this question? Thank you.

**Comment by urialon** [comment]
Hi,
Thank you for your interest in code2vec.

Can you please provide the full command line that you ran, and the full error including line numbers?

@eladn just keeping you in the loop.

By the way, our newer [code2seq](http://code2seq.org) performs better, even if all you need is a code vector.

**Comment by lishi0927** [comment]
Okay， Thank you for your reply. 
I know code2seq and  i will also experience that project.


---------------------------------------------------------------------------

our full command line:
python3 code2vec.py --load models/java14_model/saved_model_iter8 --test data/java14m/java14m.test.c2v
2019-10-20 13:20:24.347096: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-20 13:20:24.388386: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.388946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.785
pciBusID: 0000:01:00.0
2019-10-20 13:20:24.391120: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-20 13:20:24.430557: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-20 13:20:24.449705: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-20 13:20:24.456238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-20 13:20:24.501686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-20 13:20:24.530734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-20 13:20:24.614895: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-20 13:20:24.615013: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.615612: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.616246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-20 13:20:24.617057: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-20 13:20:24.650212: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3598055000 Hz
2019-10-20 13:20:24.651214: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x40b7150 executing computations on platform Host. Devices:
2019-10-20 13:20:24.651230: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-10-20 13:20:24.767940: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.768414: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x46a5160 executing computations on platform CUDA. Devices:
2019-10-20 13:20:24.768440: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2019-10-20 13:20:24.768635: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.769049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.785
pciBusID: 0000:01:00.0
2019-10-20 13:20:24.769105: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-20 13:20:24.769134: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-20 13:20:24.769172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-20 13:20:24.769197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-20 13:20:24.769236: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-20 13:20:24.769270: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-20 13:20:24.769287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-20 13:20:24.769352: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.769804: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.770229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-20 13:20:24.770846: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-20 13:20:24.772459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-20 13:20:24.772473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-20 13:20:24.772478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-20 13:20:24.773178: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.773629: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-20 13:20:24.774067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6896 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-10-20 13:20:24,774 INFO     
2019-10-20 13:20:24,774 INFO     
2019-10-20 13:20:24,774 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:24,774 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:24,775 INFO     ---------------------- Creating word2vec model ----------------------
2019-10-20 13:20:24,775 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:24,775 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:24,775 INFO     Checking number of examples ...
2019-10-20 13:20:26,655 INFO         Number of test examples: 368445
2019-10-20 13:20:26,655 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:26,655 INFO     ----------------- Configuration - Hyper Parameters ------------------
2019-10-20 13:20:26,655 INFO     CODE_VECTOR_SIZE                          384
2019-10-20 13:20:26,655 INFO     CSV_BUFFER_SIZE                           104857600
2019-10-20 13:20:26,655 INFO     DEFAULT_EMBEDDINGS_SIZE                   128
2019-10-20 13:20:26,655 INFO     DL_FRAMEWORK                              tensorflow
2019-10-20 13:20:26,655 INFO     DROPOUT_KEEP_RATE                         0.75
2019-10-20 13:20:26,655 INFO     EXPORT_CODE_VECTORS                       False
2019-10-20 13:20:26,655 INFO     LOGS_PATH                                 None
2019-10-20 13:20:26,655 INFO     MAX_CONTEXTS                              200
2019-10-20 13:20:26,655 INFO     MAX_PATH_VOCAB_SIZE                       911417
2019-10-20 13:20:26,655 INFO     MAX_TARGET_VOCAB_SIZE                     261245
2019-10-20 13:20:26,655 INFO     MAX_TOKEN_VOCAB_SIZE                      1301136
2019-10-20 13:20:26,655 INFO     MAX_TO_KEEP                               10
2019-10-20 13:20:26,655 INFO     MODEL_LOAD_PATH                           models/java14_model/saved_model_iter8
2019-10-20 13:20:26,655 INFO     MODEL_SAVE_PATH                           None
2019-10-20 13:20:26,655 INFO     NUM_BATCHES_TO_LOG_PROGRESS               100
2019-10-20 13:20:26,655 INFO     NUM_TEST_EXAMPLES                         368445
2019-10-20 13:20:26,655 INFO     NUM_TRAIN_BATCHES_TO_EVALUATE             1800
2019-10-20 13:20:26,655 INFO     NUM_TRAIN_EPOCHS                          20
2019-10-20 13:20:26,656 INFO     NUM_TRAIN_EXAMPLES                        0
2019-10-20 13:20:26,656 INFO     PATH_EMBEDDINGS_SIZE                      128
2019-10-20 13:20:26,656 INFO     PREDICT                                   False
2019-10-20 13:20:26,656 INFO     READER_NUM_PARALLEL_BATCHES               6
2019-10-20 13:20:26,656 INFO     RELEASE                                   False
2019-10-20 13:20:26,656 INFO     SAVE_EVERY_EPOCHS                         1
2019-10-20 13:20:26,656 INFO     SAVE_T2V                                  None
2019-10-20 13:20:26,656 INFO     SAVE_W2V                                  None
2019-10-20 13:20:26,656 INFO     SEPARATE_OOV_AND_PAD                      False
2019-10-20 13:20:26,656 INFO     SHUFFLE_BUFFER_SIZE                       10000
2019-10-20 13:20:26,656 INFO     TARGET_EMBEDDINGS_SIZE                    384
2019-10-20 13:20:26,656 INFO     TEST_BATCH_SIZE                           1024
2019-10-20 13:20:26,656 INFO     TEST_DATA_PATH                            data/java14m/java14m.test.c2v
2019-10-20 13:20:26,656 INFO     TOKEN_EMBEDDINGS_SIZE                     128
2019-10-20 13:20:26,656 INFO     TOP_K_WORDS_CONSIDERED_DURING_PREDICTION  10
2019-10-20 13:20:26,656 INFO     TRAIN_BATCH_SIZE                          1024
2019-10-20 13:20:26,656 INFO     TRAIN_DATA_PATH_PREFIX                    None
2019-10-20 13:20:26,656 INFO     USE_TENSORBOARD                           False
2019-10-20 13:20:26,656 INFO     VERBOSE_MODE                              1
2019-10-20 13:20:26,656 INFO     _Config__logger                           <Logger code2vec (INFO)>
2019-10-20 13:20:26,656 INFO     context_vector_size                       384
2019-10-20 13:20:26,656 INFO     entire_model_load_path                    models/java14_model/saved_model_iter8__entire-model
2019-10-20 13:20:26,656 INFO     entire_model_save_path                    None
2019-10-20 13:20:26,656 INFO     is_loading                                True
2019-10-20 13:20:26,656 INFO     is_saving                                 False
2019-10-20 13:20:26,656 INFO     is_testing                                True
2019-10-20 13:20:26,656 INFO     is_training                               False
2019-10-20 13:20:26,656 INFO     model_load_dir                            models/java14_model
2019-10-20 13:20:26,656 INFO     model_weights_load_path                   models/java14_model/saved_model_iter8__only-weights
2019-10-20 13:20:26,656 INFO     model_weights_save_path                   None
2019-10-20 13:20:26,656 INFO     test_steps                                360
2019-10-20 13:20:26,656 INFO     train_data_path                           None
2019-10-20 13:20:26,656 INFO     train_steps_per_epoch                     0
2019-10-20 13:20:26,656 INFO     word_freq_dict_path                       None
2019-10-20 13:20:26,656 INFO     ---------------------------------------------------------------------
2019-10-20 13:20:26,656 INFO     Loading model vocabularies from: `models/java14_model/dictionaries.bin` ... 
2019-10-20 13:20:28,058 INFO     Done loading model vocabularies.
2019-10-20 13:20:28,577 INFO     Done creating code2vec model
Traceback (most recent call last):
  File "code2vec.py", line 31, in <module>
    eval_results = model.evaluate()
  File "/home/paullee/ls/code2vec/tensorflow_model.py", line 120, in evaluate
    input_iterator = tf.compat.v1.data.make_initializable_iterator(self.eval_reader.get_dataset())
  File "/home/paullee/ls/code2vec/path_context_reader.py", line 116, in get_dataset
    self._dataset = self._create_dataset_pipeline(input_data_rows)
  File "/home/paullee/ls/code2vec/path_context_reader.py", line 142, in _create_dataset_pipeline
    num_parallel_calls=self.config.READER_NUM_PARALLEL_BATCHES)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1214, in map
    self, map_func, num_parallel_calls, preserve_cardinality=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3454, in __init__
    use_legacy_function=use_legacy_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2695, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1854, in _get_concrete_function_internal
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2689, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2634, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /home/paullee/ls/code2vec/path_context_reader.py:181 _map_raw_dataset_row_to_expected_model_input_form  *
        tensors = self._map_raw_dataset_row_to_input_tensors(*row_parts)
    /home/paullee/ls/code2vec/path_context_reader.py:216 _map_raw_dataset_row_to_input_tensors  *
        assert all(tensor.shape == (self.config.MAX_CONTEXTS,) for tensor in
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:713 __hash__
        raise TypeError("Tensor is unhashable if Tensor equality is enabled. "

    TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by urialon** [comment]
What is your TensorFlow version?

**Comment by lishi0927** [comment]
2.0.0

**Comment by urialon** [comment]
Let me check and get back to you.
@eladn do you have an idea? If not, I’ll investigate

**Comment by lishi0927** [comment]
Okay, Thank you for your help.

**Comment by urialon** [comment]
Hi @lishi0927 ,
Can you please try to simply comment out the assertion line here:
[https://github.com/tech-srl/code2vec/blob/master/path_context_reader.py#L216](https://github.com/tech-srl/code2vec/blob/master/path_context_reader.py#L216)

It seems that the implementation of tensor hashing has changed in TF2.0.0, other people have reported this to TensorFlow.

Let me know if it helped

**Comment by lishi0927** [comment]
Hi, Thank you.
It make sense, but i also have to comment out the assert function in the "_filter_input_rows", line 156 in the path_context_reader.py file;
Also the default saved model in the java14_model is saved_model_iter8.release;
Finally, it gives a result:

2019-10-21 21:22:58,250 INFO     top10_acc: [0.50086444 0.54063157 0.5556596  0.56424161 0.56990053 0.57424853
 0.57761945 0.58042313 0.58295811 0.58502626], precision: 0.6582174600509684, recall: 0.5314902438062055, F1: 0.5881043842714981

**Comment by urialon** [comment]
Thank you for letting us know! I will update this in the code.
