### ISSUE TITLE
Problems using code2vec to generate java code  vectors

### ISSUE THREAD

**Issue by Gueloi** [tech-srl/code2vec#50]
Hi,  i am trying to use code2vec to generate representations(vectors) for some java code. I am using the following command:

python code2vec.py --load models/java14_model/saved_model_iter8.release  --test <file> --export_code_vectors

and a variation:

python code2vec.py --load models/java14_model/saved_model_iter8.release  --test <file_with_filepaths> --export_code_vectors

in both cases i got the following errors

2019-11-02 23:46:57.585327: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expect 201 fields but have 7 in record
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_19]]
  (1) Invalid argument: Expect 201 fields but have 7 in record
         [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2vec.py", line 31, in <module>
    eval_results = model.evaluate()
  File "/home/gustavoeloi/GU/UNICAMP/tese/code/code2vec/tensorflow_model.py", line 159, in evaluate
    self.eval_original_names_op, self.eval_code_vectors],
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expect 201 fields but have 7 in record
         [[node IteratorGetNext (defined at /home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
         [[IteratorGetNext/_19]]
  (1) Invalid argument: Expect 201 fields but have 7 in record
         [[node IteratorGetNext (defined at /home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "code2vec.py", line 31, in <module>
    eval_results = model.evaluate()
  File "/home/gustavoeloi/GU/UNICAMP/tese/code/code2vec/tensorflow_model.py", line 122, in evaluate
    input_tensors = input_iterator.get_next()
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2500, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/home/gustavoeloi/programs/anaconda3/envs/tf_gpu2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()

what should i do. Or, what am I doing wrong

**Comment by urialon** [comment]
Hi @Gueloi ,
The first option is definitely incorrect, since it uses `--test` without specifying the file name.
In the second option, <file_with_filepaths> should be a file that was prepared using the `preprocess` script.
Otherwise, if you wish to transform a java file to a vector without preprocessing, you can use the `--predict` with `--export_code_vectors`.

Best,
Uri

**Comment by Gueloi** [comment]
Thanks for your response. First, that "file" in the first command line was
just a dummy text, i used a real file. However i still having problems with
the correct syntax to transform a java file to a vector without
preprocessing.
I used --predict and --export_code_vectors, without success and got errors.
Can you exemplify with a command line example?

Em dom., 3 de nov. de 2019 às 02:50, Uri Alon <notifications@github.com>
escreveu:

**Comment by Gueloi** [comment]
Another thing. It's seems its not possible to direct specify the file which
i want to generate the code vector representation (from the penultimate
layer, i just want the representation used to predict, not the prediction).
Am I wrong?

Em seg., 4 de nov. de 2019 às 13:01, Gustavo Eloi Rodrigues <
gueloi95@gmail.com> escreveu:

**Comment by Gueloi** [comment]
Basically, i am just trying to use transfer learning. I have some code
snippets and i want a vector representation for them.

Em seg., 4 de nov. de 2019 às 13:26, Gustavo Eloi Rodrigues <
gueloi95@gmail.com> escreveu:

**Comment by urialon** [comment]
Hi,
Does `--predict` work for you, without exporting code vectors, just manually playing with the model as described [here](https://github.com/tech-srl/code2vec/#step-4-manual-examination-of-a-trained-model)?

The code currently does not support specifying the file to encode (= to generate code vector).
There are two main options: preprocessing a directory, and then transforming all examples to vectors; or, using `--predict` mode, to copy-paste the content of the method you want to encode into `Input.java` and get the prediction and the code vector.

Let me know how it goes..
