### ISSUE TITLE
--release and --export_code_vectors don't work

### ISSUE THREAD

**Issue by DavidSUN2** [tech-srl/code2vec#54]
Hi Sir,
Your work is wonderful. The code is very readable and the instruction is very understandable. Thanks a lot.
Recently I'm applying your model to another data set and everything works well except --release and --export_code_vectors. Could you please give me a hand?
I run the code through Google Colab: python 3.6.8, tensorflow-gpu 2.0.0-beta1
The commands I used are as follows:
**!python3 code2vec.py --framework keras --load models/test2vec/saved_model --release**
**!python3 code2vec.py --framework keras --load models/test2vec/saved_model --test data/my_dataset/my_dataset.test.c2v --export_code_vectors**
The two commands run well and no errors, but I can not see any files generated, i.e. *.release and *.vectors can not be generated. I don't know why. 
Could you please give me some hints? Thanks.

**Comment by DavidSUN2** [comment]
This is the --release command's results
2019-11-13 22:15:17,645 INFO     
2019-11-13 22:15:17,645 INFO     
2019-11-13 22:15:17,645 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,645 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,645 INFO     ---------------------- Creating word2vec model ----------------------
2019-11-13 22:15:17,645 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,645 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,645 INFO     Checking number of examples ...
2019-11-13 22:15:17,645 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,645 INFO     ----------------- Configuration - Hyper Parameters ------------------
2019-11-13 22:15:17,645 INFO     CODE_VECTOR_SIZE                          384
2019-11-13 22:15:17,645 INFO     CSV_BUFFER_SIZE                           104857600
2019-11-13 22:15:17,645 INFO     DEFAULT_EMBEDDINGS_SIZE                   128
2019-11-13 22:15:17,645 INFO     DL_FRAMEWORK                              keras
2019-11-13 22:15:17,646 INFO     DROPOUT_KEEP_RATE                         0.75
2019-11-13 22:15:17,646 INFO     EXPORT_CODE_VECTORS                       False
2019-11-13 22:15:17,646 INFO     LOGS_PATH                                 None
2019-11-13 22:15:17,646 INFO     MAX_CONTEXTS                              200
2019-11-13 22:15:17,646 INFO     MAX_PATH_VOCAB_SIZE                       911417
2019-11-13 22:15:17,646 INFO     MAX_TARGET_VOCAB_SIZE                     261245
2019-11-13 22:15:17,646 INFO     MAX_TOKEN_VOCAB_SIZE                      1301136
2019-11-13 22:15:17,646 INFO     MAX_TO_KEEP                               10
2019-11-13 22:15:17,646 INFO     MODEL_LOAD_PATH                           models/test2vec/saved_model
2019-11-13 22:15:17,646 INFO     MODEL_SAVE_PATH                           None
2019-11-13 22:15:17,646 INFO     NUM_BATCHES_TO_LOG_PROGRESS               100
2019-11-13 22:15:17,646 INFO     NUM_TEST_EXAMPLES                         0
2019-11-13 22:15:17,646 INFO     NUM_TRAIN_BATCHES_TO_EVALUATE             1800
2019-11-13 22:15:17,646 INFO     NUM_TRAIN_EPOCHS                          5
2019-11-13 22:15:17,646 INFO     NUM_TRAIN_EXAMPLES                        0
2019-11-13 22:15:17,646 INFO     PATH_EMBEDDINGS_SIZE                      128
2019-11-13 22:15:17,646 INFO     PREDICT                                   False
2019-11-13 22:15:17,646 INFO     READER_NUM_PARALLEL_BATCHES               6
2019-11-13 22:15:17,646 INFO     RELEASE                                   True
2019-11-13 22:15:17,646 INFO     SAVE_EVERY_EPOCHS                         1
2019-11-13 22:15:17,646 INFO     SAVE_T2V                                  None
2019-11-13 22:15:17,646 INFO     SAVE_W2V                                  None
2019-11-13 22:15:17,646 INFO     SEPARATE_OOV_AND_PAD                      False
2019-11-13 22:15:17,646 INFO     SHUFFLE_BUFFER_SIZE                       10000
2019-11-13 22:15:17,646 INFO     TARGET_EMBEDDINGS_SIZE                    384
2019-11-13 22:15:17,647 INFO     TEST_BATCH_SIZE                           1024
2019-11-13 22:15:17,647 INFO     TEST_DATA_PATH                            None
2019-11-13 22:15:17,647 INFO     TOKEN_EMBEDDINGS_SIZE                     128
2019-11-13 22:15:17,647 INFO     TOP_K_WORDS_CONSIDERED_DURING_PREDICTION  10
2019-11-13 22:15:17,647 INFO     TRAIN_BATCH_SIZE                          1024
2019-11-13 22:15:17,647 INFO     TRAIN_DATA_PATH_PREFIX                    None
2019-11-13 22:15:17,647 INFO     USE_TENSORBOARD                           False
2019-11-13 22:15:17,647 INFO     VERBOSE_MODE                              1
2019-11-13 22:15:17,647 INFO     _Config__logger                           <Logger code2vec (INFO)>
2019-11-13 22:15:17,647 INFO     context_vector_size                       384
2019-11-13 22:15:17,647 INFO     entire_model_load_path                    models/test2vec/saved_model__entire-model
2019-11-13 22:15:17,647 INFO     entire_model_save_path                    None
2019-11-13 22:15:17,647 INFO     is_loading                                True
2019-11-13 22:15:17,647 INFO     is_saving                                 False
2019-11-13 22:15:17,647 INFO     is_testing                                False
2019-11-13 22:15:17,647 INFO     is_training                               False
2019-11-13 22:15:17,647 INFO     model_load_dir                            models/test2vec
2019-11-13 22:15:17,647 INFO     model_weights_load_path                   models/test2vec/saved_model__only-weights
2019-11-13 22:15:17,647 INFO     model_weights_save_path                   None
2019-11-13 22:15:17,647 INFO     test_steps                                0
2019-11-13 22:15:17,647 INFO     train_data_path                           None
2019-11-13 22:15:17,647 INFO     train_steps_per_epoch                     0
2019-11-13 22:15:17,647 INFO     word_freq_dict_path                       None
2019-11-13 22:15:17,647 INFO     ---------------------------------------------------------------------
2019-11-13 22:15:17,648 INFO     Loading model vocabularies from: `models/test2vec/dictionaries.bin` ... 
2019-11-13 22:15:18,029 INFO     Done loading model vocabularies.
2019-11-13 22:15:18.065716: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-11-13 22:15:18.079890: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.080432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
2019-11-13 22:15:18.080715: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-11-13 22:15:18.081927: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-11-13 22:15:18.083086: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-11-13 22:15:18.083414: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-11-13 22:15:18.084779: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-11-13 22:15:18.085946: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-11-13 22:15:18.089237: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-13 22:15:18.089355: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.089949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.090465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-11-13 22:15:18.090868: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-13 22:15:18.184436: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.185267: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1d3cbc0 executing computations on platform CUDA. Devices:
2019-11-13 22:15:18.185311: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2019-11-13 22:15:18.187172: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-11-13 22:15:18.188258: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6782380 executing computations on platform Host. Devices:
2019-11-13 22:15:18.188293: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-13 22:15:18.188488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.189052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
2019-11-13 22:15:18.189110: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-11-13 22:15:18.189124: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-11-13 22:15:18.189136: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-11-13 22:15:18.189146: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-11-13 22:15:18.189160: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-11-13 22:15:18.189171: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-11-13 22:15:18.189183: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-13 22:15:18.189253: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.189880: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.190413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-11-13 22:15:18.190464: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-11-13 22:15:18.191518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-13 22:15:18.191543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-11-13 22:15:18.191554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-11-13 22:15:18.191659: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.192273: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-13 22:15:18.192836: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-11-13 22:15:18.192872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15216 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
2019-11-13 22:15:20,627 INFO     Loading entire model from path `models/test2vec/saved_model__entire-model`.
2019-11-13 22:15:20,631 INFO     Loading latest checkpoint `models/test2vec/saved_model__entire-model/ckpt-5`.
2019-11-13 22:15:22,195 INFO     Model: "model"
2019-11-13 22:15:22,195 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,195 INFO     Layer (type)                    Output Shape         Param #     Connected to                     
2019-11-13 22:15:22,195 INFO     ==================================================================================================
2019-11-13 22:15:22,196 INFO     input_1 (InputLayer)            [(None, 200)]        0                                            
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,196 INFO     input_2 (InputLayer)            [(None, 200)]        0                                            
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,196 INFO     input_3 (InputLayer)            [(None, 200)]        0                                            
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,196 INFO     token_embedding (Embedding)     (None, 200, 128)     7894656     input_1[0][0]                    
2019-11-13 22:15:22,196 INFO                                                                      input_3[0][0]                    
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,196 INFO     path_embedding (Embedding)      (None, 200, 128)     54105472    input_2[0][0]                    
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,196 INFO     concatenate (Concatenate)       (None, 200, 384)     0           token_embedding[0][0]            
2019-11-13 22:15:22,196 INFO                                                                      path_embedding[0][0]             
2019-11-13 22:15:22,196 INFO                                                                      token_embedding[1][0]            
2019-11-13 22:15:22,196 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,197 INFO     dropout (Dropout)               (None, 200, 384)     0           concatenate[0][0]                
2019-11-13 22:15:22,197 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,197 INFO     time_distributed (TimeDistribut (None, 200, 384)     147456      dropout[0][0]                    
2019-11-13 22:15:22,197 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,197 INFO     input_4 (InputLayer)            [(None, 200)]        0                                            
2019-11-13 22:15:22,197 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,197 INFO     attention (AttentionLayer)      ((None, 384), (None, 384         time_distributed[0][0]           
2019-11-13 22:15:22,197 INFO                                                                      input_4[0][0]                    
2019-11-13 22:15:22,197 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:22,197 INFO     target_index (Dense)            (None, 21507)        8258688     attention[0][0]                  
2019-11-13 22:15:22,197 INFO     ==================================================================================================
2019-11-13 22:15:22,198 INFO     Total params: 70,406,656
2019-11-13 22:15:22,198 INFO     Trainable params: 70,406,656
2019-11-13 22:15:22,198 INFO     Non-trainable params: 0
2019-11-13 22:15:22,198 INFO     __________________________________________________________________________________________________
2019-11-13 22:15:23,971 INFO     Lookup tables created.
2019-11-13 22:15:23,971 INFO     Done creating code2vec model

**Comment by urialon** [comment]
Hi,
Thank you for your interest in code2vec.

Do these two options work if you train your model without the "--framework keras" flag?

**Comment by DavidSUN2** [comment]
I have tried --release command with tensorflow without the "--framework keras" flag, the same issue happened, i.e. no file was generated.
I will try --export_code_vectors as soon as possible.

**Comment by urialon** [comment]
The question is how you trained the model, with or without this flag

**Comment by DavidSUN2** [comment]
I have tried both keras framework and tensorflow framework. 
For keras framework, I add the "--framework keras" flag just after every code2vec.py for every command including the train.sh file. everything went well including training, testing and prediction. Only release and extracting code vector don't work.
For tensorflow framework, I just used your original code. Training was ok, but I remember for the following steps, something wrong happened. Therefore, I didn't continue the tensorflow framework.
Could you please give me more hints?

**Comment by DavidSUN2** [comment]
So weired. I just tried tensorflow with the "--framework keras" flag, --export_code_vectors command works, but --release command still didn't work. --save_t2v and --save_t2v didn't work either (while keras framework works).

**Comment by urialon** [comment]
If you have a trained TensorFlow model, let me know if something doesn’t work with it

**Comment by DavidSUN2** [comment]
For the trained TensorFlow model, the following 3 commands don't work:
1.  **!python3 code2vec.py --load models/test2vec/saved_model --release**
2.  **!python3 code2vec.py --load models/test2vec/saved_model --save_w2v models/test2vec/tokens.txt**
3.  **!python3 code2vec.py --load models/test2vec/saved_model --save_t2v models/test2vec/targets.txt**
for 1, everything ran well, and no errors showed. but no .release file was generated.
for 2 and 3, errors are the same shown below:
 Traceback (most recent call last):
  File "code2vec.py", line 25, in <module>
    model.save_word2vec_format(config.SAVE_W2V, VocabType.Token)
  File "/content/gdrive/My Drive/code2vec/model_base.py", line 178, in save_word2vec_format
    vocab_embedding_matrix = self._get_vocab_embedding_as_np_array(vocab_type)
  File "/content/gdrive/My Drive/code2vec/tensorflow_model.py", line 382, in _get_vocab_embedding_as_np_array
    embeddings = tf.compat.v1.get_variable(vocab_tf_variable_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1503, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1246, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 569, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 521, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 915, in _get_single_variable
    raise ValueError("The initializer passed is not valid. It should "
ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.

Thanks~

**Comment by urialon** [comment]
As an immediate step, you can go back to commit `9789cfa0d7ee74b8dca9e2b84c45228b86716d1c` which works with TensorFlow 1.x, and everything is supposed to work there.
I'll check the current version. 
Thanks for reporting this.

**Comment by DavidSUN2** [comment]
I go back to commit 9789cfa0d7ee74b8dca9e2b84c45228b86716d1c and everything works well, but only --release still doesn't work. Anyway this is not a big deal. I'm not sure whether this is due to Google Colab. Thanks.

**Comment by urialon** [comment]
In the old commit - you are right, 
`--release`  will work only if you add a dummy `--test something` flag.
So the command line will be:
```
code2vec.py --load models/test_model/saved_model_iter8 --release --test blabla
```

**Comment by DavidSUN2** [comment]
Hi Uri,
I have tried the command with the dummy flag. It works. Based on my experience these days, the old commit can work perfectly in Google Colab.

One more thing I want to confirm with you: I have tried transfer learning using your trainable model (here I mean the tensorflow 2.0.0-beta1 version, the framework I use keras): I used a totally new dataset with different token size, path size and target/label size, and the targets are different from your targets; I continue training the model using my new dataset based on your trainable model. Everything ran well and no errors occurred. So I guess this works. I'm reading your code and need a little bit time. One confusion is that : the keras model summary generates the total new model structure(i.e. the shape of each layer and the number of parameters are all based on my new dataset, not the original model's hyperparamters). So do you think the transfer learning works? Any ideas? Thanks.

**Comment by urialon** [comment]
Hi,
So you loaded the model, and then continued training on the new dataset?

In general, it makes sense, but if the model summary generates the total new model structure, I'm not sure that it uses the weights from the old model.

Another issue is that the old vocabularies are loaded from the saved model, so the new targets might be all "unknown".

**Comment by DavidSUN2** [comment]
Hi Uri, thanks for your reply.
I used the following command:
**!source train.sh --load models/java14m_trainable/saved_model --data data/my_dataset/my_dataset.train.c2v --save data/**
my_dataset.train.c2v is the new dataset. The new token vocab. size, new path vocab. size and target vocab. size are different from yours, and the target/labels are also different from yours. The other things (e.g. max context, embedding size) are the same.
I will check the code detailedly. Thanks.

**Comment by skarimik** [comment]
Hi Uri, This is a wonderful work, however I am facing this issue with the --release flag too.
And I am curious to know about your timeline on resolving the issue.
Thanks.

**Comment by urialon** [comment]
Hopefully in a few days.
But can't you use the old version in which "release" works?

**Comment by skarimik** [comment]
Thanks for the quick reply.
And thank you for your effort in resolving this issue.
I will look into using the old version but I think the Tenserflow version will be a problem for me when using the older version.

**Comment by DavidSUN2** [comment]
Sorry, @skarimik I thought you have finished your question.
For the older version(https://github.com/tech-srl/code2vec/tree/9789cfa0d7ee74b8dca9e2b84c45228b86716d1c) , I use tensorflow 1.15.0 through Google Colab. Everything works fine.

**Comment by Muralitharan2789** [comment]
As per requirements.txt in latest code2vec comit, I am using tensorflow==2.0.0-beta1.

I have trained different java programs

Getting same release issue '' everything ran well, and no errors showed. but no .release file was generated"

code2vec.py --load models/test_model/saved_model_iter8 --release --test blabla

Thanks

**Comment by urialon** [comment]
Hi @Muralitharan2789,
As discussed previously in this thread - 
please use commit `9789cfa0d7ee74b8dca9e2b84c45228b86716d1c` which works with TF1, the `release` option is broken in the TF2 version.

**Comment by urialon** [comment]
Hi all - @Muralitharan2789, @skarimik , and @DavidSUN2 ,
I fixed the `--release` flag for using the TF model in the latest commit (TensorFlow2).
It is supposed to work now, even without the dummy `--test` flag.

So the following command should work, I tested it locally on TF2:
```
code2vec.py --load models/test_model/saved_model_iter8 --release
```

**Comment by Muralitharan2789** [comment]
Thanks, Will check and update

**Comment by urialon** [comment]
Hi all,
I think it was @DavidSUN2 who was interested in this - 
the flags `--save_w2v` and `--save_t2v` are now fixed in the latest commit, with TensorFlow 2 framework.
I still haven't fixed the keras version, but for TF2 it is supposed to work. Let me know if there are any additional issues with the TF2 version.

Thanks again for finding these bugs.
