### ISSUE TITLE
Dataset issue in preprocess 

### ISSUE THREAD

**Issue by brownies11** [tech-srl/code2vec#86]
I am so interested in your project Code2Vec and want to use it. However, these is an issue when I use my own dataset, which is a small dataset. Could you please have a look at it?

**Note: In each file(training, validation and test), a file called Xproject which has all java files and sub-directories. The same dataset of Xproject is used for training, validation and test.**

My configuration: 
TRAIN_DIR=Users/brownies/Downloads/Xproject-Code2Vec/training
VAL_DIR=Users/brownies/Downloads/Xproject-Code2Vec/validation
TEST_DIR=Users/brownies/Downloads/Xproject-Code2Vec/test
DATASET_NAME=Ga
MAX_CONTEXTS=200
WORD_VOCAB_SIZE=1301136
PATH_VOCAB_SIZE=911417
TARGET_VOCAB_SIZE=261245
NUM_THREADS=64
PYTHON=python3
 

Then I run preprocess as shown below with error.
MacBook-Pro:code2vec-master brownies$ source preprocess.sh
Extracting paths from validation set...
  File "JavaExtractor/extract.py", line 69
    p.starmap(ParallelExtractDir, zip(itertools.repeat(args), dirs))
    ^
IndentationError: unexpected indent
Finished extracting paths from validation set
Extracting paths from test set...
  File "JavaExtractor/extract.py", line 69
    p.starmap(ParallelExtractDir, zip(itertools.repeat(args), dirs))
    ^
IndentationError: unexpected indent
Finished extracting paths from test set
Extracting paths from training set...
  File "JavaExtractor/extract.py", line 69
    p.starmap(ParallelExtractDir, zip(itertools.repeat(args), dirs))
    ^
IndentationError: unexpected indent
Finished extracting paths from training set
Creating histograms from the training data

**Comment by urialon** [comment]
Hi @brownies11,
What happens if you preprocess the Java-small dataset?
Did you change anything in the code?
What is your python version? `python3 --version`

**Comment by brownies11** [comment]
**Thank you for your response. 

- If I preprocess your dataset, it generates c2v files. For main small dataset, it does not work.
- I did not change anything in the code expect the file path of dataset.
- my python version is 3.8.2.
- I use Pycharm in MacOS.

Just to make sure that I did not change anything, I reworked in a new Code2Vec project with changing dataset path. 

TRAIN_DIR=Users/brownies/Downloads/Xproject-Code2Vec/training
VAL_DIR=Users/brownies/Downloads/Xproject-Code2Vec/validation
TEST_DIR=Users/brownies/Downloads/Xproject-Code2Vec/test
DATASET_NAME=my_dataset
MAX_CONTEXTS=200
WORD_VOCAB_SIZE=1301136
PATH_VOCAB_SIZE=911417
TARGET_VOCAB_SIZE=261245
NUM_THREADS=64
PYTHON=python3

This is the result.** 



MacBook-Pro:code2vec-master brownies$ source preprocess.sh
Extracting paths from validation set...
Traceback (most recent call last):
  File "JavaExtractor/extract.py", line 94, in <module>
    subdirs = get_immediate_subdirectories(args.dir)
  File "JavaExtractor/extract.py", line 17, in get_immediate_subdirectories
    return [(os.path.join(a_dir, name)) for name in os.listdir(a_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'my_val_dir'
Finished extracting paths from validation set
Extracting paths from test set...
Traceback (most recent call last):
  File "JavaExtractor/extract.py", line 94, in <module>
    subdirs = get_immediate_subdirectories(args.dir)
  File "JavaExtractor/extract.py", line 17, in get_immediate_subdirectories
    return [(os.path.join(a_dir, name)) for name in os.listdir(a_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'my_test_dir'
Finished extracting paths from test set
Extracting paths from training set...
Traceback (most recent call last):
  File "JavaExtractor/extract.py", line 94, in <module>
    subdirs = get_immediate_subdirectories(args.dir)
  File "JavaExtractor/extract.py", line 17, in get_immediate_subdirectories
    return [(os.path.join(a_dir, name)) for name in os.listdir(a_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'my_train_dir'
Finished extracting paths from training set
Creating histograms from the training data
File: my_dataset.test.raw.txt
Traceback (most recent call last):
  File "preprocess.py", line 133, in <module>
    num_examples = process_file(file_path=data_file_path, data_file_role=data_role, dataset_name=args.output_name,
  File "preprocess.py", line 69, in process_file
    print('Average total contexts: ' + str(float(sum_total) / total))
ZeroDivisionError: float division by zero

**Comment by urialon** [comment]
See the errors:
In your first message there was a problem with parsing the preprocess.py script. Which is very weird, I suspect that you used python 2?

In your second message, there was another problem: "No such file or directory: 'my_test_dir'". 
It looks like you did not change the default paths.

**Comment by urialon** [comment]
Closing due to inactivity, feel free to re-open if you have any questions.
