### ISSUE TITLE
no dictionaries.bin after training the trainable model

### ISSUE THREAD

**Issue by YawWQ** [tech-srl/code2vec#92]
Hi, 

I met a problem when evaluating the model. I processed the dataset and downloaded the trainable model. I trained the model with the new dataset but met a problem:

_Traceback (most recent call last):
  File "code2vec.py", line 19, in <module>
    model = load_model_dynamically(config)
  File "code2vec.py", line 13, in load_model_dynamically
    return Code2VecModel(config)
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/tensorflow_model.py", line 38, in __init__
    super(Code2VecModel, self).__init__(config)
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/model_base.py", line 47, in __init__
    self.vocabs = Code2VecVocabs(config)
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/vocabularies.py", line 161, in __init__
    self._load_or_create()
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/vocabularies.py", line 170, in _load_or_create
    "Expecting file `{vocabularies_load_path}`.".format(vocabularies_load_path=vocabularies_load_path))
ValueError: Model dictionaries file is not found in model load dir. Expecting file `models/dictionaries.bin`._

So I did not get the file "dictionaries.bin". But how can I generate it?

The command I used to train the model:

_python3 code2vec.py --load models/java14m_trainable/saved_model_iter8 --data data/small_dataset/small_dataset --save models/java14withSmall_

Files I got:

_checkpoint  java14withSmall.data-00000-of-00001  java14withSmall.index	java14withSmall.meta_

Could you give me any advice? Thanks for your excellent work!

**Comment by urialon** [comment]
Hi, 
Sorry for the delayed response, was the problem solved?

**Comment by YawWQ** [comment]
> Hi,
> Sorry for the delayed response, was the problem solved?

Yes, it seems that dictionaries.bin won't be saved if set EPOCH to 1. I set EPOCH to 8 and got the file. However, I met another problem when starting evaluation after training the model for 1 EPOCH. It this because I didn't set the test dataset path in config.py? Thanks for your patience!

_...
2020-08-15 04:02:53,413 INFO     Average loss at batch 600: 0.000805, 	throughput: 158 samples/sec
/nobackup/sc19y3l/envCode2Vec/code2vec/models/java14withSmall/dictionaries.bin
2020-08-15 04:08:41,774 INFO     Saved after 1 epochs in: /nobackup/sc19y3l/envCode2Vec/code2vec/models/java14withSmall/java14withSmall_iter1
2020-08-15 04:08:48,182 INFO     Starting evaluation
Traceback (most recent call last):
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
	 [[{{node IteratorGetNext_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2vec.py", line 23, in <module>
    model.train()
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/tensorflow_model.py", line 95, in train
    evaluation_results = self.evaluate()
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/tensorflow_model.py", line 160, in evaluate
    self.eval_original_names_op, self.eval_code_vectors],
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
	 [[node IteratorGetNext_1 (defined at /nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]

Original stack trace for 'IteratorGetNext_1':
  File "code2vec.py", line 23, in <module>
    model.train()
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/tensorflow_model.py", line 95, in train
    evaluation_results = self.evaluate()
  File "/nobackup/sc19y3l/envCode2Vec/code2vec/tensorflow_model.py", line 122, in evaluate
    input_tensors = input_iterator.get_next()
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2500, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/nobackup/sc19y3l/envCode2Vec/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()_

**Comment by urialon** [comment]
You need to specify the validation path using the --test flag.
Have you not specified it?

**Comment by YawWQ** [comment]
> You need to specify the validation path using the --test flag.
> Have you not specified it?

No. It works after specifying -- test flag! Thank u so much!!  :D
