### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by yemao616** [tech-srl/code2vec#94]
Hi, 

hope you are doing well!
I am currently trying to apply your code2vec on a multiclassification task for C programs with [astminer](https://github.com/JetBrains-Research/astminer) extractor. And I got the error as below for when ran train.sh. 
> If using Keras pass *_constraint arguments to layers.
2020-10-07 20:21:07,277 INFO     Number of trainable params: 3152384
2020-10-07 20:21:07,277 INFO     variable name: model/WORDS_VOCAB:0 -- shape: (1005, 128) -- #params: 128640
2020-10-07 20:21:07,277 INFO     variable name: model/TARGET_WORDS_VOCAB:0 -- shape: (5, 384) -- #params: 1920
2020-10-07 20:21:07,277 INFO     variable name: model/ATTENTION:0 -- shape: (384, 1) -- #params: 384
2020-10-07 20:21:07,277 INFO     variable name: model/PATHS_VOCAB:0 -- shape: (22453, 128) -- #params: 2873984
2020-10-07 20:21:07,277 INFO     variable name: model/TRANSFORM:0 -- shape: (384, 384) -- #params: 147456
2020-10-07 20:21:08,013 INFO     Initalized variables
2020-10-07 20:21:10,674 INFO     Started reader...
2020-10-07 20:21:13.632289: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at sparse_to_dense_op.cc:128 : Invalid argument: indices[585] = [194,3] is out of bounds: need 0 <= index < [200,3]
Traceback (most recent call last):
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_PathContextReader._map_raw_dataset_row_to_expected_model_input_form_481}} indices[585] = [194,3] is out of bounds: need 0 <= index < [200,3]
	 [[{{node SparseToDense}}]]
	 [[IteratorGetNext]]

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "code2vec.py", line 23, in <module>
    model.train()
  File "/Users/Ye/Dropbox/Research/CodeEmbedding/OJclassification/CodeToVec/tensorflow_model.py", line 81, in train
    _, batch_loss = self.sess.run([optimizer, train_loss])
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/Users/Ye/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[585] = [194,3] is out of bounds: need 0 <= index < [200,3]
	 [[{{node SparseToDense}}]]
	 [[IteratorGetNext]]
2020-10-07 20:21:13.963726: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at sparse_to_dense_op.cc:128 : Invalid argument: indices[549] = [182,3] is out of bounds: need 0 <= index < [200,3]
[Process completed]

I noticed that this error is very similar to the one [here](https://github.com/tech-srl/code2seq/issues/4) in **code2seq**, but there is no setting for `MAX_PATH_LENGTH` in **code2vec**.  Any clue for this error? 
Thank you so much!

**Comment by urialon** [comment]
Hi @yemao616 ,
I think that the problem is that there is an extra comma (",") in one of the paths, and the comma is also the character that we use as a delimiter between the "path" and its two "tokens".

I see the error: `[194,3] is out of bounds`, which means that one of the contexts (the 195'th) has at least 4 "fields", while it should have only 3 fields (when you split by comma), like: "my|string,Expression|ForStmt|IfStmt|Assign,hello|world"

Verify that astminer does not output commas, or that it replaces them with another character.

Best,
Uri

**Comment by yemao616** [comment]
Thank you so much for the quick reply, Uri! Really appreciate it.
And yes, it turns out that I messed up the path_context format after the modification to the output of astminer. It goes well now. Thanks!

Could you please clarify the topk_acc? I tried code2vec on a small dataset first for 4-label classification. I originally thought it gives the accuracy score for the **`topk`** labels. Then I checked the `top_words`, it should give a list of predicted labels and ranked by the probability if I am correct. 

In the following example, the label `97c` is the predicted label since it is the first value of top_words, and the original label is `104c` (I modified _common.normalize_word_ and _common.legal_method_names_checker_ to accept labels with number)
> original_name: 104c
top_words: ['97c', '67c', '92c', '104c', '<PAD_OR_OOV>']
filtered_top_words: ['97c', '67c', '92c', '104c']
original_subtokens: Counter({'104c': 1})
predicted_subtokens: Counter({'97c': 1})

That is, the label in top_words list may have a different index for each sample. Then what is the point for the topk_acc if the indices are not consistent? Also, this [line](https://github.com/tech-srl/code2vec/blob/master/tensorflow_model.py#L509) , why all the value of `[suggestion_idx:self.top_k]` plus one instead of `suggestion_idx` only? And where should I get the overall accuracy score?

Here is the output of train.sh 
> top10_acc: [0.29  0.575 0.755 1.    1.    1.    1.    1.    1.    1.   ], precision: 0.29, recall: 0.29, F1: 0.29

I am a little confused with the output number, and hope makes myself clear for the question.
Thank you again for your help!

**Comment by urialon** [comment]
Hi @yemao616 ,
The "topk" metric basically means: the fraction of test examples where the correct label is within the top-k predictions.
This is meaningful in realistic settings - imagine a code completion model that suggests some possible completions. 
You don't necessarily need the correct prediction to appear *first*, you only want the correct prediction to appear within the top-5 predictions or so.

So for example, if the correct label ("original_name") was predicted 3rd, then it would be considered as "correct" in top-3, top-4, top-5...
In your case, if there are only 4 possible classes and you would (hypothetically) used top-4, you'll get a top-4 accuracy of 100%. 
(as you can see in your top10_acc - indeed the accuracy is 1 starting from the 4th entry)

I hope this helps?
Best,
Uri

**Comment by yemao616** [comment]
Thank you so much for your reply, Uri.
It definitely helps! Then the k from topk should equal to the number of labels I have if I am correct.

FYI, I tried to train a model for cpp programs which contain 100 labels where different labels mean different programming problems. training:validation = 30k : 10k. I trained with the default parameters but got really pool result, **`top1_acc = 0.01, f1=0.01`**.  nearly like a random guess. 
> variable name: model/WORDS_VOCAB:0 -- shape: (6709, 128) -- #params: 858752
variable name: model/TARGET_WORDS_VOCAB:0 -- shape: (101, 384) -- #params: 38784
variable name: model/PATHS_VOCAB:0 -- shape: (226091, 128) -- #params: 28939648 

 Is there any clue to improve it? Or just code2vec not applicable here? Thank you again for your help!

Best,
Ye

**Comment by urialon** [comment]
Hi @yemao616 ,
Of course, the IDs **must** be consistent across training/val/test. 

Regarding OOV - they are automatically changed to OOV tokens/paths by the reader, you don't need to worry about it.

By the way, check also our [code2seq](https://code2seq.org/) model. Even if your task is classification, code2**seq**
Just feed code2seq with target sequences of "length of 1". 

Best, 
Uri
